---

- name: "Boot vg-docker-01"
  gather_facts: true
  hosts:  vg-docker-01
  become: yes
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
    - docker