name: "Ubuntu workflow"


on:
  push:
    branches: [ master ]
  schedule:
      - cron:  '0 0 * * 0' #At 00:00 on Sunday every week

jobs:

  ubuntu-1604-virtualenv-job:
    name: "ubuntu-16.04 virtualenv job"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "Pull Jenkins from the public repo"
      run: sudo docker build -t jenkinsci:latest . --file dockerfiles/Dockerfile.plugins            
    - name: "List images"
      run: sudo docker image ls 

  ubuntu-1804-virtualenv-job:
    name: "ubuntu-18.04 virtualenv job"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "python3 virtualenv"
      run: |
        pip3 install virtualenv
        virtualenv -p $(which python3) ~venvpy3
        source ~venvpy3/bin/activate
        pip install -r requirements.txt 
        virtualenv --version
        pip list
        sudo docker pull jenkins/jenkins:lts-jdk11 
        sudo docker image ls
        deactivate

  ubuntu-2004-virtualenv-job:
    name: "ubuntu-20.04 virtualenv job"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "python3 virtualenv"
      run: |
        pip3 install virtualenv
        virtualenv -p $(which python3) ~venvpy3
        source ~venvpy3/bin/activate
        pip install -r requirements.txt 
        virtualenv --version
        sudo docker pull jenkins/jenkins:lts-jdk11 
        sudo docker image ls
        deactivate


